#
#  Описание: основной конфигурационный файл
#

#--- Основыне настройки сервера ---
Server:
    Name: 'modem-daemon'                                      #имя сервера

    Type: 'asynchronous'                                #тип сервера (synchronous/asynchronous)

    #--- Настройка сетевого соединения ---
    Connection:
        ip_version: 4                                 #версия ip аддреса (ip_v4 или ip_v6)
        ip_address: '0.0.0.0'                           #ip адресс
        port: 9618                                     #порт

    #--- Основные директрии сервера ---
    Directories:
        #--- Настройки лог файлов ---
        Logs:
            error_log: '/var/log/modem-daemon/error_log'      #директрия до файла ошибок
            access_log: '/var/log/modem-daemon/access_log'    #директрия для файла выолненных действий

        #--- Настройки pid файла ---
        Pid:
            pid_path: '/var/run/modem-daemon.pid'             #директрия до pid файла
