# Конфигурация демона key-sender

# общие настройки
common:
    ifname: 'mfhss0'
    ipaddr: '192.168.1.3' # кого пингует
    login: 'root'
    password: 'root'
    srcfile: '/root/keys'  # файл с ключами
    dstdir: '/mnt/configs/' # куда кидать по ssh
	
#ping настройки
ping:
    ifname: 'br0' # с какого интерфейса пингует
    timeout: 2	# сколько ждёт пинг [c]
    count: 3	# сколько раз пингует  [шт]

# ssh настройки
sshpass:
    timeout: 2	# время ожидания соединения [с]


